//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Questions { get; set; }
        public int Vote { get; set; }
        public int View { get; set; }
        public System.DateTime Date { get; set; }
        public int Answer1 { get; set; }
        public string AcceptedAnswer { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string IP { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CUserID { get; set; }
        public string MUserID { get; set; }
    }
}
